#!/bin/bash
# vim: ft=bash ts=2 sw=2 et ff=unix fenc=utf-8

set -eu

# Part of Spotify-cli
# Pause playing

##### Load libraries
_CURDIR="$(cd $(dirname $0) ; pwd)"
LIBSPDIR=${LIBSPDIR:="${_CURDIR}/.."}     # (Caution) varies according to _CURDIR
CONFDIR=${CONFIDR:="${LIBSPDIR}/config"}
source ${CONFDIR}/basic_settings
source ${COMMONDIR}/http_status

##### API
URLBASE="https://api.spotify.com/v1"
API="me/player/play"

##### Processing body
ACCESS_TOKEN=$(cat ${CONFDIR}/access_token)
if [ -z "${ACCESS_TOKEN}" ]; then
  echo '{ "error": { "status": 401, "message": "The access token expired"  }  }'
  echo "${HTTP_UNAUTHORIZED}"
  exit 1
fi
HEADER_AUTH="Authorization: Bearer ${ACCESS_TOKEN}"

# curl ${1:-} -s -k -G \
#   -H "${HEADER_ALWAYS}" \
#   -H "${HEADER_AUTH}" \
#   "${URLBASE}/${API}"
#
# exit 16

[ $# -le 0  ] && (echo "not enough args"; return 1)
DEVICE_ID=$1

RESPONSE=$(curl ${1:-} -X "PUT" \
  --silent --insecure --write-out '\n\n%{http_code}\n' \
  --header "${HEADER_ALWAYS}" \
  --header "${HEADER_AUTH}" \
  "${URLBASE}/${API}?device_id=${DEVICE_ID}"
)
HTTP_CODE=$(tail -n1 <<< "${RESPONSE}")
RES_BODY=$(head -n-1 <<< "${RESPONSE}")
dprintf "RES_BODY+${RES_BODY}"
dprintf "HTTP_CODE=${HTTP_CODE}"

### Error check
case "${HTTP_CODE}" in
  # 401 Unauthorized
  "${HTTP_UNAUTHORIZED}" )
    echo "${RES_BODY}"
    echo "${HTTP_CODE}"
    exit 0
    ;;
  "4*" )
    ;;
  "5*" )
    ;;
esac

### Output
echo "${RES_BODY}"
echo "${HTTP_CODE}"
exit 0

