#!/bin/bash
# vim: ft=bash ts=2 sw=2 et ff=unix fenc=utf-8

# Part of spotify-cli
# basic_settings
# ORIGIN: 2020-12-14 by hmr

set -eu

# Already read?
[ -n "${HAVE_BASIC_SETTINGS:-""}" ] && return

##### System dependent settings
_SYSTEM=$(uname -s | tr "[A-Z]" "[a-z]")
case "${_SYSTEM}" in
  "darwin" )
    URL_OPENER="open"
    ;;

  "linux" )
    URL_OPENER=""
    ;;
esac

##### System independent settings
# Authorization redirect URL
REDIRECT_PORT="${REDIRECT_PORT:=1234}"
REDIRECT_URI="http://localhost:${REDIRECT_PORT}/callback_gen.php"

# Client ID: Don't change
CLIENT_ID="5dda0289718a42fe8411b26d2d376127"

# HTTP header to add always
HEADER_ALWAYS="Cache-Control: no-cache"

source "${LIBSPDIR}/common/internal_settings"
source "${LIBSPDIR}/common/internal_functions"
source "${LIBSPDIR}/common/http_status"

HAVE_BASIC_SETTINGS=1

