#!/bin/bash
# vim: ft=bash ts=2 sw=2 et ff=unix fenc=utf-8

set -eu

# Part of Spotify-cli
# Authorization Code Flow with Proof Key for Code Exchange (PKCE)
# Requesting a refreshed access token

##### Load libraries
_CURDIR="$(cd $(dirname $0) ; pwd)"
LIBSPDIR=${LIBSPDIR:="${_CURDIR}/.."}     # (Caution) varies according to _CURDIR
CONFDIR=${CONFIDR:="${LIBSPDIR}/config"}
source ${CONFDIR}/basic_settings
source ${COMMONDIR}/http_status

##### API
#URLBASE="http://localhost:8080"   # for debug with netcat
URLBASE="https://accounts.spotify.com"
API="api/token"

##### Processing body
GRANT_TYPE="refresh_token"
REFRESH_TOKEN="$(<${CONFDIR}/refresh_token)"
if [ -z "${REFRESH_TOKEN}"  ]; then
  echo "${R_PREFIX}:${R_UNAUTH}:${HTTP_UNAUTHORIZED}" 1>&2
  exit ${HTTP_UNAUTHORIZED}
fi
TOKEN_EPOCH="$(<${CONFDIR}/token_epoch)"
if [ -z "${TOKEN_EPOCH}"  ]; then
  echo "${R_PREFIX}:${R_UNAUTH}:${HTTP_UNAUTHORIZED}" 1>&2
  exit ${HTTP_UNAUTHORIZED}
fi

CURRENT_EPOCH="$(get_epoch)"
echo "Duration: $((${CURRENT_EPOCH} - ${TOKEN_EPOCH})) " > ${CONFDIR}/duration
if [ $((${CURRENT_EPOCH} - ${TOKEN_EPOCH})) -le 3540 ]; then
  echo "${R_PREFIX}:${R_SUCCESS}:${HTTP_OK}" 1>&2
  exit 0
fi

# curl ${1:-} --silent --insecure --write-out '\n\n%{http_code}\n' \
#   --header "${HEADER_ALWAYS}" \
#   --data-urlencode "client_id=${CLIENT_ID}" \
#   --data-urlencode "grant_type=${GRANT_TYPE}" \
#   --data-urlencode "refresh_token=${REFRESH_TOKEN}" \
#   "${URLBASE}/${API}"
#
# exit 16

RESPONSE=$(curl ${1:-} --silent --insecure --write-out '\n\n%{http_code}\n' \
  --header "${HEADER_ALWAYS}" \
  --data-urlencode "client_id=${CLIENT_ID}" \
  --data-urlencode "grant_type=${GRANT_TYPE}" \
  --data-urlencode "refresh_token=${REFRESH_TOKEN}" \
  "${URLBASE}/${API}"
)

HTTP_CODE=$(tail -n1 <<< "${RESPONSE}")
RES_BODY=$(head -n-1 <<< "${RESPONSE}")

# Error check
if [ "${HTTP_CODE}" -ne "${HTTP_OK}" ]; then
  echo "${R_PREFIX}:${R_FAIL}:${HTTP_CODE}" 1>&2
  exit ${HTTP_CODE}
fi

# Output
ACCESS_TOKEN=$(echo ${RES_BODY} | jq -r '.access_token')
REFRESH_TOKEN=$(echo ${RES_BODY} | jq -r '.refresh_token')

# JSON error check
if [ -z "${ACCESS_TOKEN}" -o -z "${REFRESH_TOKEN}" ]; then
  echo "${R_PREFIX}:${R_JSON}:${HTTP_UNAUTHORIZED}" 1>&2
  exit ${HTTP_UNAUTHORIZED}
fi

# Success
echo $(get_epoch) > ${CONFDIR}/token_epoch
echo -n "${ACCESS_TOKEN}"  > ${CONFDIR}/access_token
echo -n "${REFRESH_TOKEN}" > ${CONFDIR}/refresh_token

echo "${R_PREFIX}:${R_SUCCESS}:${HTTP_CODE}" 1>&2
exit 0

